sudo: false
language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - 5.1.0

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm i -g npm@latest

before_script:
  - npm prune
  - npm install react react-motion invariant pr1ntr/redux redux-act redux-thunk reselect core-decorators lodash@4.0.1 classnames
  - cd node_modules/redux && npm install && npm run build:lib

script:
  - npm run test

after_success:
  - npm run coverage
  - npm run semantic-release

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
